# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:RD51DgU5/w5zuemSZmo2PUunGbzKB8Fl,iv:16sfu1zJRQBdpaBMdm8vAPBgELYwekTqDvwNR7/xvbI=,tag:Z8nvBtnXDwf/F127AFWhtA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:2jYaL3hwlS1keVEUqCzRRofKxaj6cAG9bM+TgyMDIMHutWmVUg==,iv:ZK17Mzabn+KRfdXuvveUlry3ZR9R6mH1csmtZOeVrXA=,tag:E12SRzSCSA8K1x6nk/PpXA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:7Lx4w7F2ov1tWFDXGGk0Lg==,iv:lD7pkE9sBSS8WVrBgyu710eUhic5VLkPMFc1Nn2IMbw=,tag:OwJ7bKKV55oKi6sKeG2wmg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ynzhn59vjy0tp87dnzjlxypukffskcga5dtgu3raz3r5jspja5fq99a8a8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBObVJnMmNXMnMxSVR0Ukxa
            S0E3QWZ4QWZXZlQ1WWV1MUpxUVpmdGpta1dFCkEwajZwTGlkbDc5azBjUGNUQUph
            NTVyVUxNS2pNaEc1SUo0c1dVdlJZY00KLS0tIG43dElqeDBTLy9oTlhHVTlnclNI
            VnRqYWV3bFUrYjliUVZOWm8xUlQ0dzgKXm52h9SfE0iF3gjedB11vDaIqIHU9Yxf
            VhtH0JeEcevyR7TJFP2hFbSPI2+TSz6hb3PhBokVDz2usCeux/0q2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-07T21:17:17Z"
    mac: ENC[AES256_GCM,data:tlEn3oKmLCny1KqnN7WJYMRp+PEoh4BeoudJGNLOJcjCMeVBIEYZ8mXo0XHb9WrbT40ifQK9b+Hwd9UigGtq9r+V3927kGBDArCxDdIwOL3js1wzvh8jLAmAnkw9q1P5NJaiHy3rLD3XR6G7Df5uD2mlxwvPQ4VLVPvsNlVgzBc=,iv:ha+Zs8saEqxjQVyvURwXkoT2tUtAgRMyOY3P+SCoZBM=,tag:E404i0IVCeSU3oIikax5xg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
