# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: networking
stringData:
    api-key: ENC[AES256_GCM,data:dftyU2g0EztZuN3GWyaPcVwsgrGH7JQRCOGk6OMyWraTP09lQQ==,iv:1Jp1miqBvaT/pzsTNA7WmsF9CQxHLJnc5RzUOJ/981w=,tag:SbDyJBcwzps+GXjI4chlEg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ynzhn59vjy0tp87dnzjlxypukffskcga5dtgu3raz3r5jspja5fq99a8a8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdndoVk5STld5eU4zUXFB
            RVJVak5tVXNrOC94dlpXVFJjSXNBbjRpeWkwCjcxd2RrdXdtVENiU2NBR1NRbHZN
            a3Bid1d4dEU4NUdqeUlnYVBXZXVNUXcKLS0tIHk3YzgxQXJTaG9PT3RvRGZ1S0NW
            ZUpBd0pIcHNYL3JYSHBPbTY2ck9QeWMKAgn77eBfcR8fSYe+/usqclITwS+QSaDY
            N1CCqLChWCEmgHmLLpgyl4KzmVGiAK0mlcPm7LBdCqSJqFpjrOsaFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-07T21:17:17Z"
    mac: ENC[AES256_GCM,data:5D0e+otgA1LQabwYNUFSkiGG6GvUSkvDjRgDwRihLOVYrYxrMGxK+KpBO77cb3tKN4yiUr3qXsK5slCm1JKaDZfJclVwVId3TPL6Juu7l4wH8k9Q5wM5JiR0KxmQ7uo4UMM6Yjrp1jLsG7w605c0ekqxHC1zQCAdcChslklHZsQ=,iv:SZLp0FYtNjawMdbPMLR4CcfvYhpYAi8MkSiY5HAtU8A=,tag:j6F5VD3jLIeF+S/2+bPYUQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
