---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: Europe/Ljubljana
  METALLB_LB_RANGE: 192.168.30.200-192.168.30.240
  METALLB_K8S_GATEWAY_ADDR: 192.168.30.200
  METALLB_INGRESS_ADDR: 192.168.30.201
