kind: Secret
ansible_user: ENC[AES256_GCM,data:WyvkBPpGgJ4=,iv:W9o7AIThfFwj8+AxJfSMyiYPG7K/Yg9Rk5bRjZ00MT0=,tag:p7b4pLKjIfcpIvcsm+l+yA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:6axb/+SrriYmjMFSCQg=,iv:x9Lv2Wy4yYtaLMvMfuJNWJjnShUZYFTfthn7Lwrr0vY=,tag:Urxs/swiSV4SDjh0xVPCaA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ynzhn59vjy0tp87dnzjlxypukffskcga5dtgu3raz3r5jspja5fq99a8a8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4THp3TnpmR2dFWGwzVFFV
            TWxidmhYUjczNVZlR2M2QklZNURHd3ZSSXpJCjNTTk0xU3ZVZXppZk1lLzdvUmZp
            QktwaS9ESkdWRENFdnFtVmVmcVZ3SXcKLS0tIG1TZVdXcEN6T05DSDdsUUl2UFAz
            TURCTGV4a04vL2RSRGttSDkvMVVqbWMKIv9cQOX6+qcqD3Bq6iXqLVW/8g5uq5m9
            hkjmOst9mhfDL8INeuoWvUptX9Y4IUOZyjkziwuZ6StWYwPLmOw1Zg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-07T21:17:17Z"
    mac: ENC[AES256_GCM,data:2iAohJWMDi9dzYIvGOpqWAEsRSOL8RnMRO6RNXrGguk1q8FDVoQR3IbQbPNJa8KEAGnQBxgUKVOtNtFIzId9knPm7CHduDsh12Jy3fUmd2JqX5Lr3x2+5Juf9nU8jXYGmpXFUHUz2N+6lOJSYTUPfiUxRNPQa/n8z2ZR1LWhVBU=,iv:aRGzG5X8KQVzdLHnOluy8lF/5/Q1OinjouEajlo19f0=,tag:wFAn0JNYrCK9iAKo9lXxag==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
