# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:FY1oMmrr01FG0y32pwAVjvEKLPU2o652kNjQK/sJUpJN+8eyYnj21Q==,iv:U/vR7EqxH4fkBe5YTogLiHUSZ6+SNkKC3U01OQdmJos=,tag:SECBgPHY4UYJwg8Jz11xew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ynzhn59vjy0tp87dnzjlxypukffskcga5dtgu3raz3r5jspja5fq99a8a8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKM0x2dUM2cnZBUmtyZ2Fp
            TGk0bjdhQVhFUXdQd0hpMmw5WXJNQkozcVFRCk1XOStJcDVPNlBzS3h6a0RjZFVL
            OWdUNi95bHIwRUNxYnJXSmJydm53T3cKLS0tIENyWkF3WmozS1BuNXFxK0VPVVJO
            b2cweTUyci9GT3dldlZPM3RDNDAzMjAKnboPezSw6D+i/d3KWh9+Z/lbC+sU8QpZ
            6MIP2JSgT4h8zUDCiLqXvT3e6klpJWztG3fsMCQriUzuU0aq7wAkcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-07T21:17:17Z"
    mac: ENC[AES256_GCM,data:U9RAyfLSqWC4tOJ9N0Nu9bXFG0DZ9vmkGzhgEXVkkt9YXhDCnY4c8kTFrShlK06qIqyOHVTnCGiOdWbK/UzPk5mlr/AZLOCAw4hl8FMyeQ9db0hGd7+qvEQD+Qb4YgbXPvaHlsfczNj41M4lSY28Sfa2GtPvrirwtl2Zd62NBU0=,iv:qWwKV5c/s/0rtVgwZrpNne/pqc6ZkO1hrjQrnTDOKA4=,tag:/O0NnVKHV0IxoRYmLMZZjA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
